# F# Result

Result values in F# are useful in returning errors *or* successful results.  Handling errors can be one of the most difficult aspects of any language.  

The simplest form of error handling that leads to the poorest quality is simply throwing exceptions on every error.

```fsharp
let someError = true

if someError then failwith "Some error occurred.";;

(*
System.Exception: Some error occurred.
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in c:\git\joelvandiver.github.io\_site\_drafts\2020-02-19-fs-result.fsx:line 2
*)
```

Obvisouly with exceptions, the system stops processing on **every** error.  

Is there some way that we can continue processing errors in a function instead of failing on every error?

```fsharp
let isLessThan5 x : Result<int, string> = 
    if x < 5
    then Error "The value must be less than 5."
    else Ok x

// val isLessThan5 : x:int -> Result<int,string>
```